version: "3.9"

services:
  workspace:
    container_name: ${PROJECT_NAME:-node}-workspace
    build:
      context: ./docker/workspace
      args:
        USER_NAME: ${USER_NAME:-vscode}
        USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        NODE_VERSION: ${NODE_VERSION:-v18.12.1}
        LOCALE: ${LOCALE:-en_US.UTF-8}
    tty: true
    environment:
      TZ: ${TIME_ZONE:-Asia/Tokyo}
      DB_USER: ${DB_USER:-dbuser}
      DB_PASSWORD: ${DB_PASSWORD:-thisIsReallyStrongPassword123}
      DB_NAME: ${DB_NAME:-dev}
    volumes:
      - ../:/home/${USER_NAME:-vscode}/workspace:cached
      - ~/.aws:/home/${USER_NAME:-vscode}/.aws
    ports:
      - ${WORKSPACE_PORT:-9999}:9999

  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    container_name: ${PROJECT_NAME:-node}-mongodb-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-dbuser}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-thisIsReallyStrongPassword123}
      MONGO_INITDB_DATABASE: ${DB_NAME:-dev}
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - ../.docker/mongodb:/data/db

  # url -> http://localhost:8081 or http://host-ip:8081
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: ${PROJECT_NAME:-node}-mongo-express-container
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER:-dbuser}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD:-thisIsReallyStrongPassword123}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST:-mongodb}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT:-27017}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_CONFIG_MONGODB_ENABLE_ADMIN:-true}
    depends_on:
      - mongodb